apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfd-master
  namespace: node-feature-discovery
spec:
  template:
    spec:
      containers:
        - name: nfd-master
          command:
            - "nfd-master"
            - "--resource-labels=gpu.intel.com/memory.max,gpu.intel.com/millicores"
            - "--extra-label-ns=gpu.intel.com"
